#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

am=$(xrandr --listactivemonitors | grep Monitors | cut -d " " -f 2)

if [ $am -eq 1 ]; then
    connected=$(xrandr --query | grep -v disconnected | grep connected | wc -l)
    while [ $connected -eq 1 ]
    do
        connected=$(xrandr --query | grep -v disconnected | grep connected | wc -l)
    done
    #xrandr --output DP-4 --auto --output DP-0 --auto --right-of DP-4
    mons -e right
    sleep 1
    picom &
else
    picom &
fi

bspc monitor DP-4 -d I II III IV
bspc monitor DP-0 -d V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config single_monocle       true

bspc config top_padding 30

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^5' state=fullscreen
bspc rule -a mplayer2 state=floating
bspc rule -a KeePass2 state=floating
bspc rule -a discord desktop='^3' state=fullscreen
bspc rule -a Steam desktop='^4' state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop='^2' state=fullscreen follow=on

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload main --config=/home/sepp/.config/polybar/config.ini &
done

# add wallpaper
feh --bg-scale /usr/share/wallpapers/small-memory-4k_1540749683.jpg

~/.config/bspwm/spotify-terminal
# start brave at start
brave
