#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# check ob ein oder beide Monitore angeschlossen sind
monitors=$(bspc query -M --names | wc -l)
if [ $monitors -eq 2 ]; then
	bspc monitor $(bspc query -M --names | sed -n "1p") -d I II III IV
	bspc monitor $(bspc query -M --names | sed -n "2p") -d V VI VII VIII
# nur 1 Monitor connected
elif [ $monitors -eq 1 ]; then
	bspc monitor $(bspc query -M --names) -d I II III IV V VI VII VIII
# Fallback
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width          2
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focused_border_color  "#2bcec2"
bspc config presel_feedback_color "#c678dd"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a KeePass2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^5' follow=on
bspc rule -a Steam desktop='^3' state=floating follow=on
bspc rule -a Emacs desktop='^2' state=fullscreen follow=on
bspc rule -a firefox:Toolkit sticky=on state=floating rectangle=800x600+4300+820


# Hintergrundbild setzen
#feh --bg-scale --no-xinerama ~/Bilder/Wallpaper/nightcity2dual.jpg
feh --bg-center ~/Bilder/Wallpaper/wallpaper_mikael_gustafsson.png

# Compositor
picom -b --config ~/.config/picom/picom.conf

# Theme
#wal -R

# zscroll
killall zscroll

# Spotifyd
killall spotifyd
spotifyd --no-daemon &

# autostart kitty
pgrep -x alacritty > /dev/null
if [ $? -eq 1 ];
	then alacritty -e tmux &
fi

# autostart firefox
pgrep -x firefox > /dev/null
if [ $? -eq 1 ];
	then firefox &
fi

# Statusbar
killall polybar
polybar bar &

# mount hetzner fs
sshfs -o allow_other sepp@server.jstout.de:/home/sepp /mnt/server
