#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d I II III IV
bspc monitor DP-4 -d V VI VII VIII

bspc config border_width          2
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focused_border_color  "#2bcec2"
bspc config presel_feedback_color "#c678dd"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a KeePass2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^5' follow=on
bspc rule -a Steam desktop='^2' follow=on
bspc rule -a firefox:Toolkit sticky=on state=floating rectangle=800x600+4300+820


# Hintergrundbild setzen
#feh --bg-scale --no-xinerama ~/Bilder/Wallpaper/nightcity2dual.jpg
feh --bg-center ~/Bilder/Wallpaper/wallpaper_mikael_gustafsson.png

# Compositor
picom -b --config ~/.config/picom/picom.conf

# Theme
#wal -R

# zscroll
killall zscroll

# Spotifyd
killall spotifyd
spotifyd --no-daemon &

# autostart kitty
pgrep -x alacritty > /dev/null
if [ $? -eq 1 ];
	then alacritty &
fi

# autostart firefox
pgrep -x firefox > /dev/null
if [ $? -eq 1 ];
	then firefox &
fi

# Statusbar
killall polybar
polybar bar &

# mount hetzner fs
sshfs -o allow_other sepp@server.jstout.de:/home/sepp /mnt/server
