#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# check ob ein oder beide Monitore angeschlossen sind
monitors=$(bspc query -M --names | wc -l)
if [ $monitors -eq 2 ]; then
	bspc monitor $(bspc query -M --names | sed -n "1p") -d I II III IV
	bspc monitor $(bspc query -M --names | sed -n "2p") -d V VI VII VIII
# nur 1 Monitor connected
elif [ $monitors -eq 1 ]; then
	bspc monitor $(bspc query -M --names) -d I II III IV V VI VII VIII
# Fallback
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width          2
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focused_border_color  "#2bcec2"
bspc config presel_feedback_color "#c678dd"

bspc config -d V window_gap 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a KeePassXC state=floating center=on
bspc rule -a KeePass2 state=floating center=on
bspc rule -a Screenkey manage=off
#bspc rule -a firefoxesr desktop='^5' follow=on
bspc rule -a firefox-esr state=floating
bspc rule -a Steam desktop='^3' state=floating follow=off
bspc rule -a discord desktop='^4' state=floating follow=on
bspc rule -a Emacs desktop='^2' state=fullscreen follow=on
bspc rule -a firefox-esr:Toolkit sticky=on state=floating rectangle=800x600+4300+820


# Hintergrundbild setzen
#feh --bg-scale --no-xinerama ~/Bilder/Wallpaper/nightcity2dual.jpg
#feh --bg-center ~/Bilder/Wallpaper/portal_to_another_world.png
#feh --bg-center ~/Bilder/Wallpaper/sun-line-2560×1440.jpg
feh --bg-fill ~/Bilder/Wallpaper/alena-aenami-autumn-in-budapest-1920×1080.jpg

# Compositor
picom -b --config ~/.config/picom/picom.conf

# Theme
#wal -R

# zscroll
killall zscroll
killall polybar
polybar bar &

# Spotifyd
killall spotifyd
spotifyd --no-daemon &

# autostart st
bspc rule -a st --one-shot desktop='^1'
pgrep -x st > /dev/null
if [ $? -eq 1 ];
	then st -e tmux &
fi

# autostart firefox
bspc rule -a firefox-esr --one-shot desktop='^5' state=fullscreen
pgrep -x firefox-esr > /dev/null
if [ $? -eq 1 ];
	then firefox-esr &
fi

# start spotifyd
pgrep -x spotifyd > /dev/null
if [ $? -eq 1 ];
	then spotifyd --no-daemon &
fi


# start greenclip
pgrep -x greenclip > /dev/null
if [ $? -eq 1 ];
	then greenclip daemon &
fi
# welches audio_sink ist in Verwendung?
pgrep -x check_current_sink > /dev/null
if [ $? -eq 1 ];
	then check_current_sink &
fi
