#! /bin/sh

logfile=/tmp/bspwm_external_rules.log
wid=$1
class=$2
instance=$3
consequences=$4

if [ "$instance" = Steam ] ; then
	title=$(xtitle "$wid")
	if [ "$title" = "Friends List" ] ; then
		echo "split_ratio=0.85"
	elif [[ "$title" =~ "Steam - News" ]]; then
    echo "foo" >> "$logfile"
		echo "state=floating"
		echo "rectangle=800x600+2180+770"
	elif [ "$title" != "Steam" ]; then
		echo "state=floating"
		echo "rectangle=800x600+2180+770"
	fi
fi

echo "ID: $wid" >> "$logfile"
echo "CLASS: $class" >> "$logfile"
echo "INSTANCE: $instance" >> "$logfile"
echo "TITLE: $title" >> "$logfile"
