#!/usr/bin/bash

running_sink=$(pactl list short | grep RUNNING)
i=0
while [[ -z $running_sink && $i -lt 10 ]]; do
	sleep 1
        running_sink=$(pactl list short | grep RUNNING)
	let i++
done
if [[ $running_sink == *"Headset"* ]]; then
	echo ""

else
	echo "蓼"
fi
