require("js.options")
require("gitsigns").setup()
require("nvim-autopairs").setup {}
require("js.lspconfig")
require("js.feline")
require("js.telescope")
require("js.colorscheme")
require("js.treesitter")
require("js.cmp")
require("colorizer").setup()
